package com.example.journalapp.data

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a single journal entry in the database.
 *
 * @property id The unique identifier for the journal entry. Auto-generated by the database.
 * @property title The title of the journal entry.
 * @property content The main content of the journal entry.
 * @property date The timestamp of when the entry was created or last modified.
 */
@Entity(tableName = "journal_entries")
public data class JournalEntry(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0,
    val title: String = "",
    val content: String = "",
    val date: Long = 0,
)
